version: '3.8'
services:
  server:
    build:
      dockerfile: dev.dockerfile
      context: ./server
    restart: always
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - ./server/src:/app/src
      - ./server/nodemon.json:/app/nodemon.json
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - SERVER_PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=postgres
      - JWT_SECRET=DOOMED
  db:
    image: postgres:14.7-alpine
    restart: always
    ports:
      - 5433:5432
    volumes:
      - db-data:/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256

volumes:
  db-data: {}